/* Generated by Together */

package CompositePattern.src.filesystem;

public class FileNode extends FileSystemNode {
    public FileNode() {
    }

    public int getSize() {
        return this.size;
    }
    private  void setSize(int size){
        this.size= size;
    }
    private int size=0;

}
