/* Generated by Together */

package CommandPattern.src.demo3;

public interface MacroCommand extends Command {
    void execute();

     void remove(Command toRemove);

     void add(Command toAdd);
}
